# Generated by Django 3.2.6 on 2021-08-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostelecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='canvas',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
