# Generated by Django 3.2.6 on 2021-08-21 09:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostelecom', '0002_alter_project_canvas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='canvas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), default=None, size=None),
        ),
    ]
